/*
 * SPDX-FileCopyrightText: 2015 - 2026 Rime community
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package com.osfans.trime.ime.compose.theme

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

/**
 * Pins the type weights and the panel sizes of [ImeTokens] (popup, symbol panel, panel lists, input
 * bar, edit panel), so a change to any of them is a deliberate one.
 */
class ImeTokensTest :
    StringSpec({
        fun table(t: ImeTokens) = mapOf<String, Any>(
            "keyTextWeight" to t.keyTextWeight.weight,
            "keyLabelWeight" to t.keyLabelWeight.weight,
            "keySymbolWeight" to t.keySymbolWeight.weight,
            "candidateWeight" to t.candidateWeight.weight,
            "candidateHighlightWeight" to t.candidateHighlightWeight.weight,
            "candidateCommentWeight" to t.candidateCommentWeight.weight,
            "preeditWeight" to t.preeditWeight.weight,
            "popupWeight" to t.popupWeight.weight,
            "panelTitleWeight" to t.panelTitleWeight.weight,
            "panelLabelWeight" to t.panelLabelWeight.weight,
            "panelBodyWeight" to t.panelBodyWeight.weight,
            "keyCornerRadius" to t.keyCornerRadius,
            "keyIconSize" to t.keyIconSize,
            "keySymbolIconSize" to t.keySymbolIconSize,
            "enterKeyPill" to t.enterKeyPill,
            "keyPressedFunctionSwap" to t.keyPressedFunctionSwap,
            "keyboardCornerRadius" to t.keyboardCornerRadius,
            "candidateHighlightPaddingHorizontal" to t.candidateHighlightPaddingHorizontal,
            "candidateHighlightPaddingVertical" to t.candidateHighlightPaddingVertical,
            "candidateHighlightCornerRadius" to t.candidateHighlightCornerRadius,
            "preeditCornerRadius" to t.preeditCornerRadius,
            "panelSwitchTileCornerRadius" to t.panelSwitchTileCornerRadius,
            "popupAnchorGap" to t.popupAnchorGap,
            "popupPreviewCornerRadius" to t.popupPreviewCornerRadius,
            "popupShadowElevation" to t.popupShadowElevation,
            "popupKeyboardCellWidth" to t.popupKeyboardCellWidth,
            "popupKeyboardCellHeight" to t.popupKeyboardCellHeight,
            "popupKeyboardTextSize" to t.popupKeyboardTextSize,
            "popupKeyboardPadding" to t.popupKeyboardPadding,
            "popupKeyboardCornerRadius" to t.popupKeyboardCornerRadius,
            "popupKeyboardHighlightCornerRadius" to t.popupKeyboardHighlightCornerRadius,
            "symbolCellMinWidth" to t.symbolCellMinWidth,
            "symbolLongTextHorizontalPadding" to t.symbolLongTextHorizontalPadding,
            "symbolSideBarWidth" to t.symbolSideBarWidth,
            "panelListPadding" to t.panelListPadding,
            "panelCellSpacing" to t.panelCellSpacing,
            "panelEntryTextSize" to t.panelEntryTextSize,
            "panelEntryPaddingHorizontal" to t.panelEntryPaddingHorizontal,
            "panelEntryPaddingVertical" to t.panelEntryPaddingVertical,
            "panelEntryMaxLines" to t.panelEntryMaxLines,
            "panelEntryPinSize" to t.panelEntryPinSize,
            "panelEntryPinAlpha" to t.panelEntryPinAlpha,
            "panelSwitchCellMinWidth" to t.panelSwitchCellMinWidth,
            "panelSwitchCellHeight" to t.panelSwitchCellHeight,
            "panelSwitchTileSize" to t.panelSwitchTileSize,
            "panelSwitchIconSize" to t.panelSwitchIconSize,
            "panelSwitchGlyphTextSize" to t.panelSwitchGlyphTextSize,
            "panelSwitchLabelTextSize" to t.panelSwitchLabelTextSize,
            "panelSegmentPaddingHorizontal" to t.panelSegmentPaddingHorizontal,
            "panelSegmentPaddingVertical" to t.panelSegmentPaddingVertical,
            "panelSegmentMargin" to t.panelSegmentMargin,
            "panelSegmentEdgeScrollZone" to t.panelSegmentEdgeScrollZone,
            "panelSegmentEdgeScrollStep" to t.panelSegmentEdgeScrollStep,
            "panelBarIconSize" to t.panelBarIconSize,
            "panelDisabledAlpha" to t.panelDisabledAlpha,
            "panelMenuTextSize" to t.panelMenuTextSize,
            "panelEmptyHintTextSize" to t.panelEmptyHintTextSize,
            "panelEmptyHintAlpha" to t.panelEmptyHintAlpha,
            "barUnrollButtonWidth" to t.barUnrollButtonWidth,
            "barIconButtonPadding" to t.barIconButtonPadding,
            "barIconButtonCornerRadius" to t.barIconButtonCornerRadius,
            "barClipboardIconSize" to t.barClipboardIconSize,
            "barClipboardSpacing" to t.barClipboardSpacing,
            "barClipboardMaxTextWidth" to t.barClipboardMaxTextWidth,
            "barClipboardVerticalMargin" to t.barClipboardVerticalMargin,
            "barClipboardCornerRadius" to t.barClipboardCornerRadius,
            "barClipboardPreviewLength" to t.barClipboardPreviewLength,
            "barInlinePinnedHorizontalMargin" to t.barInlinePinnedHorizontalMargin,
            "barTabSpacing" to t.barTabSpacing,
            "barUnrolledItemMinWidth" to t.barUnrolledItemMinWidth,
            "editPanelCommandColumnFraction" to t.editPanelCommandColumnFraction,
            "editPanelCenterColumnWeight" to t.editPanelCenterColumnWeight,
            "editPanelArrowIconSize" to t.editPanelArrowIconSize,
            "editPanelIconSize" to t.editPanelIconSize,
            "editPanelLabelTextSize" to t.editPanelLabelTextSize,
            "editPanelIconLabelGap" to t.editPanelIconLabelGap,
            "editPanelLabelBesideIcon" to t.editPanelLabelBesideIcon,
            "t9ColumnItemHeight" to t.t9ColumnItemHeight,
            "t9ColumnItemSpacing" to t.t9ColumnItemSpacing,
            "t9ColumnMinTextSize" to t.t9ColumnMinTextSize,
            "t9ColumnTextHorizontalPadding" to t.t9ColumnTextHorizontalPadding,
            "voicePillHeight" to t.voicePillHeight,
            "voicePillHorizontalPadding" to t.voicePillHorizontalPadding,
            "voicePillIconSize" to t.voicePillIconSize,
            "voicePillContentGap" to t.voicePillContentGap,
            "voicePillTextSize" to t.voicePillTextSize,
            "voicePillMessageMaxLines" to t.voicePillMessageMaxLines,
            "voicePillCaretGap" to t.voicePillCaretGap,
            "voicePillScreenMargin" to t.voicePillScreenMargin,
            "voicePillShadowElevation" to t.voicePillShadowElevation,
            "voiceLevelBarWidth" to t.voiceLevelBarWidth,
            "voiceLevelBarGap" to t.voiceLevelBarGap,
            "voiceLevelBarMinHeight" to t.voiceLevelBarMinHeight,
            "voiceLevelBarMaxHeight" to t.voiceLevelBarMaxHeight,
            "voiceKeyLevelSpread" to t.voiceKeyLevelSpread,
            "voiceKeyLevelAlpha" to t.voiceKeyLevelAlpha,
        )

        "portrait values" {
            table(ImeTokens.Portrait) shouldBe expectedPortrait
        }

        "landscape values" {
            table(ImeTokens.Landscape) shouldBe expectedLandscape
        }
    })

// field → original value; the same tables passed against the old token objects before the merge
private val expectedPortrait: Map<String, Any> = mapOf(
    // type weights on the app font's axis
    "keyTextWeight" to 500,
    "keyLabelWeight" to 550,
    "keySymbolWeight" to 400,
    "candidateWeight" to 450,
    "candidateHighlightWeight" to 500,
    "candidateCommentWeight" to 400,
    "preeditWeight" to 400,
    "popupWeight" to 500,
    "panelTitleWeight" to 600,
    "panelLabelWeight" to 500,
    "panelBodyWeight" to 400,
    // shapes
    "keyCornerRadius" to 10.dp,
    "keyIconSize" to 24.dp,
    "keySymbolIconSize" to 13.dp,
    "enterKeyPill" to true,
    "keyPressedFunctionSwap" to false,
    "keyboardCornerRadius" to 16.dp,
    "candidateHighlightPaddingHorizontal" to 8.dp,
    "candidateHighlightPaddingVertical" to 4.dp,
    "candidateHighlightCornerRadius" to 50.dp,
    "preeditCornerRadius" to 12.dp,
    "panelSwitchTileCornerRadius" to 16.dp,
    // key preview bubble and popup keyboard
    "popupAnchorGap" to 2.dp,
    "popupPreviewCornerRadius" to 14.dp,
    "popupShadowElevation" to 3.dp,
    "popupKeyboardCellWidth" to 44.dp,
    "popupKeyboardCellHeight" to 48.dp,
    "popupKeyboardTextSize" to 24.sp,
    "popupKeyboardPadding" to 4.dp,
    "popupKeyboardCornerRadius" to 16.dp,
    "popupKeyboardHighlightCornerRadius" to 10.dp,
    // symbol panel
    "symbolCellMinWidth" to 48.dp,
    "symbolLongTextHorizontalPadding" to 4.dp,
    "symbolSideBarWidth" to 64.dp,
    // panel lists
    "panelListPadding" to 4.dp,
    "panelCellSpacing" to 6.dp,
    "panelEntryTextSize" to 15.sp,
    "panelEntryPaddingHorizontal" to 10.dp,
    "panelEntryPaddingVertical" to 8.dp,
    "panelEntryMaxLines" to 4,
    "panelEntryPinSize" to 12.dp,
    "panelEntryPinAlpha" to 0.3f,
    "panelSwitchCellMinWidth" to 88.dp,
    "panelSwitchCellHeight" to 96.dp,
    "panelSwitchTileSize" to 48.dp,
    "panelSwitchIconSize" to 24.dp,
    "panelSwitchGlyphTextSize" to 20.sp,
    "panelSwitchLabelTextSize" to 12.sp,
    "panelSegmentPaddingHorizontal" to 8.dp,
    "panelSegmentPaddingVertical" to 4.dp,
    "panelSegmentMargin" to 4.dp,
    "panelSegmentEdgeScrollZone" to 10.dp,
    "panelSegmentEdgeScrollStep" to 12.dp,
    "panelBarIconSize" to 24.dp,
    "panelDisabledAlpha" to 0.38f,
    "panelMenuTextSize" to 16.sp,
    "panelEmptyHintTextSize" to 14.sp,
    "panelEmptyHintAlpha" to 0.6f,
    // input bar
    "barUnrollButtonWidth" to 40.dp,
    "barIconButtonPadding" to 4.dp,
    "barIconButtonCornerRadius" to 20.dp,
    "barClipboardIconSize" to 20.dp,
    "barClipboardSpacing" to 4.dp,
    "barClipboardMaxTextWidth" to 220.dp,
    "barClipboardVerticalMargin" to 4.dp,
    "barClipboardCornerRadius" to 20.dp,
    "barClipboardPreviewLength" to 42,
    "barInlinePinnedHorizontalMargin" to 10.dp,
    "barTabSpacing" to 8.dp,
    "barUnrolledItemMinWidth" to 40.dp,
    // edit panel
    "editPanelCommandColumnFraction" to 0.28f,
    "editPanelCenterColumnWeight" to 1.4f,
    "editPanelArrowIconSize" to 30.dp,
    "editPanelIconSize" to 22.dp,
    "editPanelLabelTextSize" to 14.sp,
    "editPanelIconLabelGap" to 2.dp,
    "editPanelLabelBesideIcon" to false,
    // t9 pinyin column
    "t9ColumnItemHeight" to 36.dp,
    "t9ColumnItemSpacing" to 4.dp,
    "t9ColumnMinTextSize" to 8.sp,
    "t9ColumnTextHorizontalPadding" to 2.dp,
    // voice
    "voicePillHeight" to 28.dp,
    "voicePillHorizontalPadding" to 9.dp,
    "voicePillIconSize" to 16.dp,
    "voicePillContentGap" to 4.dp,
    "voicePillTextSize" to 13.sp,
    "voicePillMessageMaxLines" to 2,
    "voicePillCaretGap" to 4.dp,
    "voicePillScreenMargin" to 8.dp,
    "voicePillShadowElevation" to 3.dp,
    "voiceLevelBarWidth" to 2.5.dp,
    "voiceLevelBarGap" to 2.dp,
    "voiceLevelBarMinHeight" to 3.dp,
    "voiceLevelBarMaxHeight" to 12.dp,
    "voiceKeyLevelSpread" to 3.dp,
    "voiceKeyLevelAlpha" to 0.24f,
)

// a 40dp row takes smaller corners, glyphs and highlight insets; popup cells shrink; edit panel labels move beside their glyphs
private val expectedLandscape: Map<String, Any> = expectedPortrait + mapOf(
    "keyCornerRadius" to 8.dp,
    "keyIconSize" to 22.dp,
    "keySymbolIconSize" to 12.dp,
    "candidateHighlightPaddingHorizontal" to 6.dp,
    "candidateHighlightPaddingVertical" to 3.dp,
    "preeditCornerRadius" to 10.dp,
    "popupKeyboardCellHeight" to 40.dp,
    "popupKeyboardTextSize" to 22.sp,
    "editPanelArrowIconSize" to 26.dp,
    "editPanelIconSize" to 20.dp,
    "editPanelIconLabelGap" to 6.dp,
    "editPanelLabelBesideIcon" to true,
    "t9ColumnItemHeight" to 28.dp,
    "voicePillHeight" to 24.dp,
    "voicePillIconSize" to 14.dp,
    "voicePillTextSize" to 12.sp,
    "voiceLevelBarMaxHeight" to 10.dp,
)
