/*
 * SPDX-FileCopyrightText: 2015 - 2026 Rime community
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package com.osfans.trime.data.hotwords

import com.osfans.trime.data.base.DataManager
import com.osfans.trime.util.appContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import timber.log.Timber
import java.io.File

/**
 * A word the user wants ahead of everything the dictionaries offer, e.g. `okok`
 * instead of `哦可哦可`.
 *
 * [code] is what has to be typed on the 26-key layout; empty means "the letters of
 * [text]". The nine-key layout derives its digit code from that with the usual
 * 2–9 mapping, so one entry serves both keyboards.
 */
@Serializable
data class HotWord(
    val text: String,
    val code: String = "",
    val weight: Int = 1,
) {
    val effectiveCode: String
        get() = code.ifBlank { HotWordManager.defaultCode(text) }
}

/**
 * Stores the hot words in the app's private storage (so a Git pull or an external
 * folder import never touches them) and turns them into the two Rime tables the
 * schemas mount before every deploy:
 *
 *  - `custom_phrase_user.txt`: stabledb custom phrases for the 26-key schema
 *  - `hotwords_t9_user.dict.yaml`: a compiled dictionary for the nine-key schema
 *    (librime's user dictionaries cannot match purely numeric codes exactly)
 */
object HotWordManager {
    private const val STORE_FILE_NAME = "hot_words.json"
    const val PHRASE_FILE_NAME = "custom_phrase_user.txt"
    const val T9_DICT_FILE_NAME = "hotwords_t9_user.dict.yaml"
    const val T9_DICT_NAME = "hotwords_t9_user"

    private val json = Json {
        ignoreUnknownKeys = true
        prettyPrint = true
    }

    private val storeFile: File
        get() = File(appContext.filesDir, STORE_FILE_NAME)

    private val lock = Any()

    @Volatile
    private var cache: List<HotWord>? = null

    fun getAll(): List<HotWord> =
        cache ?: synchronized(lock) {
            cache ?: load().also { cache = it }
        }

    private fun load(): List<HotWord> =
        runCatching {
            if (storeFile.isFile) json.decodeFromString<List<HotWord>>(storeFile.readText()) else emptyList()
        }.getOrElse {
            Timber.e(it, "Failed to read hot words")
            emptyList()
        }

    fun save(words: List<HotWord>) {
        synchronized(lock) {
            storeFile.parentFile?.mkdirs()
            storeFile.writeText(json.encodeToString(words))
            cache = words
        }
    }

    /** Letters of the word, lower-cased: the code on a 双拼/拼音 26-key layout. */
    fun defaultCode(text: String): String = text.lowercase().filter { it in 'a'..'z' }

    /** Nine-key code: letters mapped to 2–9, digits kept, everything else dropped. */
    fun t9Code(code: String): String =
        buildString {
            for (c in code.lowercase()) {
                when (c) {
                    in '0'..'9' -> append(c)
                    in 'a'..'c' -> append('2')
                    in 'd'..'f' -> append('3')
                    in 'g'..'i' -> append('4')
                    in 'j'..'l' -> append('5')
                    in 'm'..'o' -> append('6')
                    in 'p'..'s' -> append('7')
                    in 't'..'v' -> append('8')
                    in 'w'..'z' -> append('9')
                    else -> Unit
                }
            }
        }

    /** Strip everything Rime's tab-separated tables cannot hold. */
    fun sanitizeText(text: String): String = text.trim().replace(Regex("[\\t\\r\\n]+"), " ")

    fun sanitizeCode(code: String): String = code.lowercase().filter { it in 'a'..'z' || it in '0'..'9' }

    /**
     * Regenerate both tables in [dir]. Called right before Rime starts a deploy,
     * after any Git/external import has replaced the placeholders shipped with
     * the config repository.
     */
    fun writeRimeFiles(dir: File = DataManager.userDataDir): Result<Int> =
        runCatching {
            if (!dir.isDirectory) return@runCatching 0
            val words =
                getAll()
                    .map { it.copy(text = sanitizeText(it.text), code = sanitizeCode(it.effectiveCode)) }
                    .filter { it.text.isNotEmpty() && it.code.isNotEmpty() }
                    .sortedByDescending { it.weight }
            val phrases =
                buildString {
                    appendLine("# Generated by Trime from the hot word list; edit it in Trime, not here.")
                    appendLine("# text<Tab>code<Tab>weight")
                    for (w in words) appendLine("${w.text}\t${w.code}\t${w.weight}")
                }
            val dict =
                buildString {
                    appendLine("# Rime dictionary")
                    appendLine("# encoding: utf-8")
                    appendLine("# Generated by Trime from the hot word list; edit it in Trime, not here.")
                    appendLine("---")
                    appendLine("name: $T9_DICT_NAME")
                    appendLine("version: \"${System.currentTimeMillis()}\"")
                    appendLine("sort: by_weight")
                    appendLine("use_preset_vocabulary: false")
                    appendLine("columns:")
                    appendLine("  - text")
                    appendLine("  - code")
                    appendLine("  - weight")
                    appendLine("...")
                    appendLine()
                    for (w in words) {
                        val t9 = t9Code(w.code)
                        if (t9.isNotEmpty()) appendLine("${w.text}\t$t9\t${w.weight}")
                    }
                    // An empty dictionary fails to compile; the nine-key layout has no
                    // 0 key, so this entry can never be reached.
                    appendLine("占位\t0\t0")
                }
            writeIfChanged(File(dir, PHRASE_FILE_NAME), phrases)
            // the version line changes every time, so compare the entries only
            val dictFile = File(dir, T9_DICT_FILE_NAME)
            val currentEntries = if (dictFile.isFile) dictFile.readText().substringAfter("...\n", "") else null
            if (currentEntries != dict.substringAfter("...\n")) dictFile.writeText(dict)
            Timber.i("Hot words: wrote ${words.size} entries to ${dir.name}")
            words.size
        }.onFailure { Timber.e(it, "Failed to write hot word tables") }

    private fun writeIfChanged(
        file: File,
        content: String,
    ) {
        if (!file.isFile || file.readText() != content) file.writeText(content)
    }
}
